Makefile
Instead of using the bash script (that gets rate limited by GH) we use go install.
=> Makefile: use go install to install kustomize

.github/workflows/publish.yaml, Dockerfile, Makefile, cmd/main.go
This PR introduces building and pushing to quay from CI
=> Build and push the image from CI

e2etests/tests/advertisement.go, e2etests/tests/validate.go, internal/community/community.go, internal/community/community_test.go, internal/controller/api_to_config.go, internal/controller/api_to_config_test.go, internal/frr/config.go, internal/frr/frr_test.go, internal/frr/templates/filters.tmpl, internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden
Support parsing community prefixes
=> Support PrefixesWithCommunity

e2etests/go.mod, e2etests/go.sum, e2etests/go.work.sum, e2etests/pkg/routes/routes.go, e2etests/tests/receiving.go, e2etests/tests/validate.go, internal/controller/api_to_config.go, internal/controller/api_to_config_test.go, internal/frr/config.go, internal/frr/frr_test.go, internal/frr/templates/filters.tmpl, internal/frr/testdata/TestSingleSession.golden, internal/frr/testdata/TestTwoSessionsAcceptAll.golden, internal/frr/testdata/TestTwoSessionsAcceptSomeV4.golden, internal/frr/testdata/TestTwoSessionsAcceptV4AndV6.golden
Here we implement the incoming routes accepting (and filtering) and we add e2e tests for it.
This is based on https://github.com/metallb/frr-k8s/pull/19 for the testing part.
Also, it will require https://github.com/metallb/metallb/pull/2001 to validate injection on dual stack.
=> Implement receiving / filtering prefixes from outside

charts/frr-k8s/README.md, charts/frr-k8s/templates/controller.yaml, charts/frr-k8s/values.yaml, cmd/main.go, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/default/frr-k8s_auth_proxy_patch.yaml, config/frr-k8s/frr-k8s.yaml, e2etests/tests/metrics.go, frr-tools/metrics/collector/bgp.go, frr-tools/metrics/collector/bgp_test.go, frr-tools/metrics/collector/metrics.go, frr-tools/metrics/exporter.go, internal/controller/frrconfiguration_controller.go, internal/controller/stats.go, internal/frr/parse.go, internal/frr/parse_test.go
Depends on https://github.com/metallb/frr-k8s/pull/33
this aligns the ports to not clash with MetalLB and adds some metrics
=> Extend metrics

internal/controller/frrconfiguration_controller.go
We do listen for secrets, so if it is added it the reconciliation will converge. By returning the error we add a lot of unnecessary loops happening before the secret is added.
=> Don't treat the non existing secret as a special error

.github/workflows/publish.yaml, api/v1beta1/frrconfiguration_types.go, charts/frr-k8s/charts/crds/templates/crds.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/crd/bases/frrk8s.metallb.io_frrconfigurations.yaml, e2etests/go.mod, e2etests/go.sum, e2etests/go.work.sum, e2etests/tests/session.go, internal/controller/api_to_config.go, internal/controller/api_to_config_test.go
Those fields were missing. Also, we do validate their values as we did in metallb.
Note: this requires https://github.com/metallb/metallb/pull/2104 to make the tests compile
=> Translate the keepalive / holdtime from api to frr

internal/frr/config.go, internal/frr/templates/filters.tmpl, internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden, internal/frr/testdata/TestMultipleRoutersMultipleNeighs.golden, internal/frr/testdata/TestSingleSession, internal/frr/testdata/TestSingleSession.golden, internal/frr/testdata/TestSingleSessionBFD.golden, internal/frr/testdata/TestSingleSessionWithEBGPMultihop.golden, internal/frr/testdata/TestSingleSessionWithEBGPMultihopAndExtras.golden, internal/frr/testdata/TestSingleSessionWithIPv6SingleHop.golden, internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden, internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden, internal/frr/testdata/TestTwoSessionsAcceptAll.golden, internal/frr/testdata/TestTwoSessionsAcceptSomeV4.golden, internal/frr/testdata/TestTwoSessionsAcceptV4AndV6.golden
Aligning to the latest changes in MetalLB, we force the sequence numbers of the prefix lists from outside to ease the job of the reloader.
=> FRR configuration: force the sequence number from the template

Makefile, api/v1beta1/frr_node_state_types.go, charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrnodestates.yaml, cmd/main.go, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/crd/bases/frrk8s.metallb.io_frrnodestates.yaml, e2etests/tests/status.go, internal/controller/common_test.go, internal/controller/frrconfiguration_controller.go, internal/controller/frrconfiguration_controller_test.go, internal/controller/frrstate_controller.go, internal/controller/frrstate_controller_test.go
This might be useful to understand why the conversion failed without having to look at the logs. The FRR status is useful, but sometimes the configuration is blocked earlier (for example when the password is missing from secrets).
Based off https://github.com/metallb/frr-k8s/pull/52
=> API: add a LastConversionResult field to the node state

.github/workflows/ci.yaml, HOW_TO_RELEASE.md, Makefile, RELEASE_NOTES.md, hack/release/bumpversion.sh, hack/release/pre_bump.sh, hack/release/release.sh
- Add a CI step to create the helm chart
- Add a makefile rule to automate the release process (with versioning the tags around the manifests)
- Create an empty release notes file
=> Release automation

Makefile, charts/frr-k8s/README.md, charts/frr-k8s/values.yaml
We don't know if the dest cluster has the prometheus operator deployed, so it's not safe to assume so by default.
Also, removing comments related to metallb alarms.
=> Charts: disable service monitors by default

RELEASE_NOTES.md, internal/controller/merge.go
We accidentally compared pointers instead of their values.
=> controller: fix merging neighbor's timers

internal/controller/dump.go
We forgot to hide cleartext passwords when we added them, we also remove the `kubectl.kubernetes.io/last-applied-configuration` annotation from the dumped config as it contains a password + redundant data.
=> dump: hide cleartext passwords

RELEASE_NOTES.md, charts/frr-k8s/templates/service-monitor.yaml
We missed templating the variable for frr's metrics port. Also moved the port conditional to where it belongs.
Fixing this will allow us to fetch the metrics as metallb's, making the integration easier:
```yaml
metricRelabelings:
- sourceLabels: [__name__]
regex: "frrk8s_bgp_(.*)"
targetLabel: "__name__"
replacement: "metallb_bgp_$1"
- sourceLabels: [__name__]
regex: "frrk8s_bfd_(.*)"
targetLabel: "__name__"
replacement: "metallb_bfd_$1"
```
=> helm: fix metricRelabelings

.gitattributes
The rel notes are appended, so it makes sense to do union instead of merging, otherwise each PR will cause a conflict.
=> Rel notes: merge with union

RELEASE_NOTES.md, api/v1beta1/frrconfiguration_webhook.go, api/v1beta1/frrconfiguration_webhook_test.go, cmd/main.go, e2etests/tests/webhooks.go
We accidently validated only against resources from the namespace the daemon is deployed on. This fixes it and modifies the relevant e2e.
=> webhook: validate resources from all namespaces

RELEASE_NOTES.md, charts/frr-k8s/README.md, charts/frr-k8s/templates/webhooks.yaml, charts/frr-k8s/values.yaml
We add an option to disable the webhook's cert rotator, this enables another entity to generate and manage the relevant secret.
=> helm: add an option to disable the webhook's cert rotation

RELEASE_NOTES.md, cmd/cidrs_test.go, cmd/main.go
Fixes parsing empty always-block flag as no cidrs specified, the current way is flawed because:
```go
elems := strings.Split("", ",")
fmt.Println(elems, ",", len(elems))
```
returns:
```go
[] , 1
```
=> Fix parsing empty always-block flag

RELEASE_NOTES.md, charts/frr-k8s/templates/webhooks.yaml
The liveness/readiness probes of the webhook pod pointed to the wrong endpoints,
essentially checking the endpoint of the daemon pod (via 127.0.0.1).
This fixes this by aligning with what we do in kustomize, probing the
pod's correct livez/healthz endpoints.
=> helm: align webhooks probes with kustomize

RELEASE_NOTES.md, charts/frr-k8s/README.md, charts/frr-k8s/templates/webhooks.yaml, charts/frr-k8s/values.yaml, cmd/main.go
When the webhook pod is redeployed multiple times in succession sometimes the requests for the webhook hang on `tls: failed to verify certificate` and it is not solved until the pod is restarted manually. While the reason the flag solves the issue is not totally clear, introducing the flag for the operator to consume is reasonable.
=> Add option to enable the rotator RestartOnSecretRefresh

.github/workflows/ci.yaml, RELEASE_NOTES.md
Assuming dependabot knows how to update a dependency, we don't want to check changes in go.mod (but also, all the generated files checks we do) on dependabot PRs.
So, we split the lint lane in a "lint" job which performs only linting, and a more generic "check generated" that does not run when dependabot files a PR.
=> CI: don't check generated files for dependabot prs

Makefile, RELEASE_NOTES.md
If there is no connectivity to the cluster, kubectl version fails and so the version check does not even get to check the version.
Here we redirect stderror so we can check the version and avoid downloading every time.
=> Makefile: ignore kubectl errors when checking the version

Makefile
Fixes `error: unknown shorthand flag: 'c' in -client`.
=> Makefile: fix kubectl

RELEASE_NOTES.md, charts/frr-k8s/templates/controller.yaml, charts/frr-k8s/templates/rbac.yaml, charts/frr-k8s/templates/service-accounts.yaml, charts/frr-k8s/templates/webhooks.yaml
Some api-resources which are namespaced lack a namespace in this helm chart.
This works fine when using `helm install`, but I'm using a `ClusterResourceSet` (rollout via a `ConfigMap` when using `cluster-api`). When using this, resources without a namespace get silently dropped.
I've taken the liberty of adding namespaces wherever required. I've also added quoting everywhere to keep the style consistent.
=> helm: add namespacing to all namespaced resources

.gitattributes
There is no need for the file anymore, as we will build the release notes out of pull requests.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```
=> Remove the gitattributes file for release notes

API-DOCS.md, api/v1beta1/frrconfiguration_types.go, charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrconfigurations.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/crd/bases/frrk8s.metallb.io_frrconfigurations.yaml, internal/controller/api_to_config.go, internal/controller/api_to_config_test.go, internal/frr/frr_test.go, internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden
/kind feature
```release-note
Expose the IPv4 or IPv6 source address to use for the BGP session through the k8s API
```
Fixes https://github.com/metallb/frr-k8s/issues/132
=> Expose src addr in the k8s API

charts/frr-k8s/README.md, charts/frr-k8s/values.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/frr-k8s/frr-k8s.yaml, e2etests/e2etest_suite_test.go, hack/demo/demo.sh, internal/frr/docker_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Bumping FRR to 9.1.0
```release-note
Bump FRR to version 9.1.0
```
=> Bump FRR to 9.1.0

charts/frr-k8s/templates/controller.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/frr-k8s/frr-cm.yaml, internal/frr/templates/bfdprofile.tmpl, internal/frr/testdata/TestSingleSessionBFD.golden, internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
FRR 8 preferred format for bfd echo-intervals is with separate transmit
/ receive timers. FRR 9.1 actually reports an error when deleting the
echo interval stanza.
Here we:
- generate an frr 8.0+ compatible frr configuration file
- declare the format of the configuration file to be 8.0 compatible
```release-note
Make the generated frr file compatible with frr 8+: split bfd echo interval in echo tx / echo rx.
```
=> Make the frr generated files compatible with 8.0+

charts/frr-k8s/templates/controller.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/frr-k8s/frr-cm.yaml
>
> /kind bug
/kind feature
> /kind design
> /kind flake
Until now we were not allowing FRR-K8s to be a listener for the BGP session. One of the use cases though is to allow node to node sessions to announce the IPs of the pods and have the overlay implemented with BGP.
Because of this, we need FRR-K8s to be able to establish a session with itself, and in order to do so it needs to be able to accept BGP connections.
```release-note
Allow FRR-K8s to accept incoming BGP connection so it can be used to establish sessions among the nodes (to …
```
=> Listen also for incoming BGP connections

e2etests/e2etest_suite_test.go, e2etests/pkg/k8s/pods.go
/kind regression
because it depends on labels, and running the test suite outside that repo (e.g. as part of the operator) might not work
```release-note
NONE
```
=> Revert "E2E: verify frrk8s daemonset is ready before tests"

e2etests/e2etest_suite_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The namespace is hardcoded, we want to make it possible to override it so we can run the tests in other deployments.
```release-note
NONE
```
=> E2E: allow setting the namespace frrk8s run in

API-DOCS.md, api/v1beta1/frrconfiguration_types.go, charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrconfigurations.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/crd/bases/frrk8s.metallb.io_frrconfigurations.yaml, e2etests/tests/session.go, e2etests/tests/webhooks.go, internal/controller/api_to_config.go, internal/controller/api_to_config_test.go, internal/controller/frrconfiguration_controller_test.go, internal/controller/merge_test.go, internal/frr/config.go, internal/frr/frr_bfd_test.go, internal/frr/frr_test.go, internal/frr/testdata/TestSingleSessionWithExternalASN.golden, internal/frr/testdata/TestSingleSessionWithInternalASN.golden
/kind feature
Adds support for FRR's "Dynamic ASN", allowing users to specify whether the peer is ibgp or ebgp without explicitly setting its asn. Leverages https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-remote-as-internal
```release-note
Add DynamicASN field for a neighbor, which allows the daemon to detect the AS number to use without explicitly setting it. The new field is mutually exclusive with the existing ASN field, and one of them must be specified for any given Neighbor. 
```
=> Add support for "Dynamic ASN"

.github/workflows/composite/collectlogs/action.yaml, e2etests/pkg/k8s/pods.go, e2etests/tests/graceful_restart.go
=> E2E: make Graceful Restart test more resilient when restarting pods takes time

e2etests/tests/metrics.go, frr-tools/metrics/collector/bgp.go, frr-tools/metrics/collector/bgp_test.go
>
/kind bug
> /kind design
> /kind flake
For each VRF we can have only one neighbor for a given address, which makes the port irrelevant.
Additionally, now that frr-k8s can accept connections too, the port can either be the one used on our side to establish the connection, or the source port in case we are accepting a bgp connection. This makes the metric labels non predictable and hard to monitor.
Because of this, here we remove the port from the label.
```release-note
The BGP metrics label corresponding to the peer does …
```
=> Remove the port from the peer metrics label

.github/workflows/composite/collectlogs/action.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Bumping the action to v4 as v2 is deprecated and not working anymore.
```release-note
NONE
```
=> Collect logs shared workflow: bump action to v4

Makefile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
The e2etests rule depends on kubectl so better build it. Also, bumping ginkgo to align to what the tests are using.
```release-note
NONE
```
=> Makefile: bump the ginkgo version and add a dependency on kubectl

charts/frr-k8s/README.md, charts/frr-k8s/templates/controller.yaml, charts/frr-k8s/templates/webhooks.yaml, charts/frr-k8s/values.yaml, cmd/main.go, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/default/frr-k8s_auth_proxy_patch.yaml, config/frr-k8s/frr-k8s.yaml
Since the existing healthz/readyz don't do much, we leverage the metrics endpoints for readiness/liveness to avoid opening another port (8081) on the host.
/kind cleanup
```release-note
NONE
```
=> Use metrics for readiness/liveness probes

internal/controller/api_to_config.go, internal/controller/api_to_config_test.go
Currently the return error for duplicate prefix
```
withLocalPref:
- prefixes:
- "4.4.4.100/32"
- "4.4.4.100/32"
localPref: 100
```
is `multiple local prefs specified for prefix 4.4.4.100/32` which is misleading.
/kind bug
```release-note
bug: throw better error when prefix for same localPref is added twice
```
=> Throw better error when prefix for same localPref is added twice

charts/frr-k8s/templates/controller.yaml, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/frr-k8s/frr-cm.yaml, e2etests/go.mod, e2etests/go.sum, e2etests/go.work.sum, e2etests/pkg/config/from_containers.go, e2etests/tests/graceful_restart.go
/kind bug
If we use learning routes, when we restart the pod those routes are gone from the k8s node. There is an option for zebra to keep them. That is useful only if Graceful restart is being used.
```release-note
Add by default the -K (graceful_restart) argument in Zebra so that learnt routes are maintained on the host when zebra process restart.
```
=> Add zebra -K argument and extend e2e testing

internal/frr/templates/filters.tmpl, internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden, internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6DisableMP.golden, internal/frr/testdata/TestMultipleRoutersImportVRFs.golden, internal/frr/testdata/TestMultipleRoutersMultipleNeighs.golden, internal/frr/testdata/TestSingleSession, internal/frr/testdata/TestSingleSession.golden, internal/frr/testdata/TestSingleSessionBFD.golden, internal/frr/testdata/TestSingleSessionWithAlwaysBlock.golden, internal/frr/testdata/TestSingleSessionWithEBGPMultihop.golden, internal/frr/testdata/TestSingleSessionWithEBGPMultihopAndExtras.golden, internal/frr/testdata/TestSingleSessionWithExternalASN.golden, internal/frr/testdata/TestSingleSessionWithGracefulRestart.golden, internal/frr/testdata/TestSingleSessionWithIPv6SingleHop.golden, internal/frr/testdata/TestSingleSessionWithInternalASN.golden, internal/frr/testdata/TestSingleUnnumberedSession.golden, internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden, internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden, internal/frr/testdata/TestTwoSessionsAcceptAll.golden, internal/frr/testdata/TestTwoSessionsAcceptSomeV4.golden, internal/frr/testdata/TestTwoSessionsAcceptV4AndV6.golden
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
There are a couple of cases where we reference a prefix list in a routemap before defining the prefix list itself.
Here we help frr and the reloader script by defining the prefix list before using it.
```release-note
NONE
```
=> Prefix lists: define before using them

e2etests/tests/session.go
The R-bit might false depend on the FRR version and we do not control the value. So we avoid that check as it does not really add value.
From https://datatracker.ietf.org/doc/html/rfc4724
Restart Flags:
This field contains bit flags related to restart.
0 1 2 3
+-+-+-+-+
|R|Resv.|
+-+-+-+-+
The most significant bit is defined as the Restart State (R)
bit, which can be used to avoid possible deadlock caused by
waiting for the End-of-RIB marker when multiple BGP speakers
peering with each other restart.  When set (value 1), this bit
indicates that the BGP speaker has restarted, and its peer MUST
NOT wait for the End-of-RIB marker from the speaker before
advertising routing information to the speaker.
The remaining bits are reserved and MUST be set to zero by the
sender and ignored by the …
=> E2E: do not assert on the R-bit for sessions with Graceful Restart

charts/frr-k8s/README.md, charts/frr-k8s/templates/webhooks.yaml, charts/frr-k8s/values.yaml, cmd/main.go, config/all-in-one/frr-k8s-prometheus.yaml, config/all-in-one/frr-k8s.yaml, config/frr-k8s/frr-k8s.yaml, config/webhook/service.yaml, internal/webhooks/frrconfiguration_webhook.go
/kind bug
> /kind design
> /kind flake
Instead of relying on the metrics port, we move to test the webhook endpoint. The webhook will declare itself ready only when the cert controller did its part and the certificate is generated correctly.
This allows the crs not to fail on creation if we apply them after checking all pods are ready (ie right after a make deploy).
Also, make the webhook port configurable.
```release-note
Declare the webhook pod to be ready only when it can serve requests, checking the webhook endpoint as …
```
=> Webhook pod: report ready / live when the webhook endpoint is ready

e2etests/tests/bgp_session_status.go
We add simple coverage for the session status resource that does not rely on the poll-interval, so that we can verify the feature on clusters where we don't have control over it.
>
> /kind bug
/kind feature
> /kind design
> /kind flake
We add simple coverage for the session status resource that does
not rely on the poll-interval, so that we can verify the feature
on clusters where we don't have control over it.
```release-note
NONE
```
=> E2E: Add a simple session status test that does not rely on polling
