- Makefile
- hack/kind.sh
Commit on top of https://github.com/metallb/frr-k8s/pull/1
Adding everything needed to spin up a cluster and deploy in a snap, plus
pinning the executables.
> Build, load on kind and deploy makefile rules

- .github/dependabot.yml
- .github/workflows/cancel.yaml
- .github/workflows/ci.yaml
- .github/workflows/stale.yaml
- .github/workflows/vulncheck_periodic.yaml
- DCO
- Makefile
- hack/checklicense.sh
- hack/lint.sh
Based on top of https://github.com/metallb/frr-k8s/pull/2
Adding basic CI to do linting, checking the licenses, makefile generation, plus dependabot, stalebot, vulncheck
> Basic CI setup

- e2etests/tests/validate.go
This was causing the tests not to catch errors.
> E2E: return error when the condition is not valid

- internal/frr/frr_test.go
- internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden
- internal/frr/testdata/TestMultipleRoutersMultipleNeighs.golden
- internal/frr/testdata/TestSingleSession.golden
- internal/frr/testdata/TestSingleSessionWithEBGPMultihop.golden
- internal/frr/testdata/TestSingleSessionWithIPv6SingleHop.golden
- internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden
Expanding the rendering tests.
> FRR: add more unit tests

- .github/workflows/ci.yaml
- Makefile
- config/all-in-one/frr-k8s.yaml
- config/default/frr-k8s_auth_proxy_patch.yaml
- config/frr-k8s/frr-k8s.yaml
- go.mod
- internal/controller/dump.go
- internal/controller/frrconfiguration_controller.go
We dump the config when running on log-level=debug
> Controller: dump the k8s config and the resulting frr one 

- e2etests/pkg/config/config.go
- e2etests/tests/advertise_and_receive.go
- e2etests/tests/advertisement.go
- e2etests/tests/receiving.go
- e2etests/tests/split.go
- internal/controller/api_to_config.go
- internal/controller/api_to_config_test.go
- internal/controller/frrconfiguration_controller.go
- internal/controller/merge.go
- internal/controller/merge_test.go
Up until now we parsed only the first FRRConfiguration, here we start handling all of them together
> Merge config

- Makefile
- e2etests/pkg/infra/infra_setup.go
- e2etests/tests/bfd.go
- e2etests/tests/metrics.go
- e2etests/tests/validate.go
- go.mod
- internal/controller/api_to_config.go
- internal/controller/api_to_config_test.go
- internal/controller/controller_test.go
- internal/frr/frr_bfd_test.go
- internal/frr/testdata/TestSingleSessionBFD.golden
- internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden
Here we enable the bfd conversion and e2e test it
> Enable BFD

- internal/controller/api_to_config.go
- internal/controller/api_to_config_test.go
As stated in the API we make sure the AllowedOut prefixes match the prefixes defined in the router.
> Enforce router prefixes on neighbors

- charts/frr-k8s/templates/controller.yaml
- charts/frr-k8s/templates/service-monitor.yaml
- charts/frr-k8s/templates/webhooks.yaml
* Set the missing volume for metrics-cert
* Align "frrk8s" -> "frr-k8s"
> Some helm chart fixes

- API-DOCS.md
- api/v1beta1/frrconfiguration_types.go
- charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrconfigurations.yaml
- config/all-in-one/frr-k8s-prometheus.yaml
- config/all-in-one/frr-k8s.yaml
- config/crd/bases/frrk8s.metallb.io_frrconfigurations.yaml
- config/samples/neighbor_with_password.yaml
- e2etests/tests/session.go
- internal/controller/api_to_config.go
- internal/controller/api_to_config_test.go
Support cleartext passwords as we do in MetalLB
> Add cleartext password support

- .github/workflows/ci.yaml
- Makefile
- RELEASE_NOTES.md
We add a MetalLB lane to make sure we aren't introducing changes that break the integration between the two projects.
> CI: Add a MetalLB E2E lane

- .github/workflows/ci.yaml
- README.md
- RELEASE_NOTES.md
- charts/frr-k8s/README.md
- charts/frr-k8s/values.yaml
- config/all-in-one/frr-k8s-prometheus.yaml
- config/all-in-one/frr-k8s.yaml
- config/frr-k8s/frr-k8s.yaml
- e2etests/e2etest_suite_test.go
- hack/demo/demo.sh
- internal/frr/docker_test.go
Allowing to peer with localhost among other fixes.
> Bump FRR to 9.0.2

- .github/pull_request_template.md
- .github/workflows/ci.yaml
- .github/workflows/classify.yaml
- HOW_TO_RELEASE.md
- hack/gen_relnotes.sh
Aligning the pr template, gh action and docs to what we now have in MetalLB.
> Release notes: align with MetalLB

- .github/workflows/publish.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```
> Bump cosign

- api/v1beta1/frrconfiguration_webhook.go
- api/v1beta1/mock_validator_test.go
- e2etests/go.mod
- e2etests/pkg/infra/infra_setup.go
- e2etests/pkg/k8s/nodes.go
- e2etests/pkg/k8s/pods.go
- e2etests/tests/metrics.go
- e2etests/tests/raw_config.go
- go.mod
- internal/frr/config.go
- internal/frr/docker_test.go
- internal/frr/parse.go
/kind cleanup
This PR updates github.com/pkg/errors -> errors package.
resolves #152
```release-note
NONE
```
> Replace errors

- internal/frr/templates/frr.tmpl
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Since we rely heavily on route maps, adding route map detail here.
```release-note
NONE
```
> Frr config: add route map detail in debug

- README.md
- api/v1beta1/bgp_session_state_types.go
- charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_bgpsessionstates.yaml
- config/all-in-one/frr-k8s-prometheus.yaml
- config/all-in-one/frr-k8s.yaml
- config/crd/bases/frrk8s.metallb.io_bgpsessionstates.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind documentation
* Add a few words about the CRD with a couple of examples.
* Add a printcolumn for the status.
```release-note
NONE
```
> Add BGPSessionState docs

- e2etests/tests/bgp_session_status.go
There is currently a bug on FRR 9.x that BFD profiles are not removed properly when a config that has BFD is replaced by one that does not, causing these tests to fail when the Clean isn't applied before the
tests themselves (because of the debouncer).
We put a temporary fix for that, to be removed
once we move to FRR 10.x or the bug is backported to FRR 9.
Fixes https://github.com/metallb/frr-k8s/issues/285
>
> /kind bug
> /kind design
/kind flake
```release-note
NONE
```
> E2E: Fix BGPSessionState CI flake

- internal/controller/api_to_config.go
- internal/controller/api_to_config_test.go
- internal/controller/merge.go
- internal/frr/config.go
/kind bug
> /kind design
> /kind flake
```release-note
```
> Validate neighbors in same router,  add interface checks

- .github/workflows/ci.yaml
- charts/frr-k8s/README.md
- charts/frr-k8s/values.yaml
- config/all-in-one/frr-k8s-prometheus.yaml
- config/all-in-one/frr-k8s.yaml
- config/frr-k8s/frr-k8s.yaml
- e2etests/e2etest_suite_test.go
- e2etests/pkg/infra/infra_setup.go
- e2etests/pkg/k8s/frrk8s.go
- e2etests/tests/bgp_session_status.go
- e2etests/tests/status.go
- frr-tools/reloader/frr-reloader.sh
/kind feature
> /kind design
> /kind flake
```release-note
Update FRR version to 10.4.1
```
> Bump frr to 10.4.1
